# .rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Disable noisy or low-value cops
Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
