inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

# --- Basic Syntax Improvements (autocorrectable) ---

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

# --- Performance Improvements (via rubocop-performance) ---

Performance/ReverseEach:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

# --- Correctness / Code Clarity ---

Lint/BooleanSymbol:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false
