version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0' -p 3000"
    # command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/rails
      - uploads_data:/rails/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
volumes:
  postgres_data:
  uploads_data:
