version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/myapp
      - uploads_data:/myapp/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE_DUMMY: 1
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
volumes:
  postgres_data:
  uploads_data:
