version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bundle exec rails s -b '0.0.0.0' -p 3000
    command: bash -c "export SECRET_KEY_BASE=$(bundle exec rails secret) && bundle exec rails s -b '0.0.0.0' -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE} # Pass this securely via environment variables
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_production
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - uploads_data:/myapp/public/uploads
    depends_on:
      - web
volumes:
  postgres_data:
  uploads_data:
